# Generated by Django 3.2.8 on 2022-07-02 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_auto_20220702_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='DireccionEntrega',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrdenItem',
        ),
    ]
